// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN_UFXe-r4U28ytAnv4wRzCpiCzqt_kzk',
    appId: '1:589614765547:web:c750512b94f65c88a9b5ae',
    messagingSenderId: '589614765547',
    projectId: 'my-talkter-flutter-app',
    authDomain: 'my-talkter-flutter-app.firebaseapp.com',
    storageBucket: 'my-talkter-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSSYYHGaMQ0yGU0b0843kJY7XatY8e13s',
    appId: '1:589614765547:android:81bd4012a3a97387a9b5ae',
    messagingSenderId: '589614765547',
    projectId: 'my-talkter-flutter-app',
    storageBucket: 'my-talkter-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-U3PG-zApzD7walAZlXKecRTg6gply2U',
    appId: '1:589614765547:ios:6f8aaf8112ee2a0ba9b5ae',
    messagingSenderId: '589614765547',
    projectId: 'my-talkter-flutter-app',
    storageBucket: 'my-talkter-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.talkter',
  );

}